import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidenav from "@/components/navigations/sidenav";
import Topnav from "@/components/navigations/topnav";

const font = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "CryptoC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="h-screen bg-customBlack grid grid-cols-[225px_1fr]">
          <Sidenav />
          <div className="flex overflow-y-auto scrollNone flex-col">
            <Topnav />
            <div className="p-4 flex-1 flex overflow-y-auto">
              <div className="flex-1 overflow-y-auto rounded-md scrollNone text-gray-300">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
